name: feature_2
description: "A new Flutter project."
publish_to: https://onepub.dev/api/ynnonoflyg/ # Remove this line if you wish to publish to pub.dev

version: 2.0.21

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  scale_framework:
    hosted: https://onepub.dev/api/ynnonoflyg
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
